# Configurações de Conexão com o Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/job_match_db
spring.datasource.username=root
spring.datasource.password=root

# Configurações do JPA/Hibernate
# "update" atualiza o schema do banco automaticamente com base nas suas entidades (Ideal para desenvolvimento)
spring.jpa.hibernate.ddl-auto=update

# Mostra as queries SQL no console (útil para debug)
spring.jpa.show-sql=true

# Formata o SQL no console para ficar mais legível
spring.jpa.properties.hibernate.format_sql=true

# Dialeto do PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# URL padrão do Ollama rodando na sua máquina
spring.ai.ollama.base-url=http://localhost:11434

# Escolha o modelo (recomendo llama3 ou mistral para estruturação de dados)
spring.ai.ollama.chat.options.model=llama3

# DICA DE OURO: Força o Ollama a trabalhar no "Modo JSON"
spring.ai.ollama.chat.options.format=json

spring.ai.ollama.chat.options.temperature=0.2